[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x', 'nodePackages.pnpm']

[phases.install]
cmds = [
  'rm -rf node_modules package-lock.json pnpm-lock.yaml lib',
  'pnpm install',
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
